# Generated by Django 5.1.2 on 2024-11-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_precinct_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
