# Generated by Django 5.1.3 on 2024-12-02 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokeDex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50, null=True)),
                ('species', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('abilities', models.TextField()),
                ('ev_yield', models.CharField(max_length=100)),
                ('catch_rate', models.CharField(max_length=100)),
                ('base_friendship', models.CharField(max_length=50)),
                ('base_exp', models.IntegerField()),
                ('growth_rate', models.CharField(max_length=50)),
                ('egg_groups', models.CharField(max_length=100)),
                ('gender_ratio', models.CharField(max_length=50)),
                ('egg_cycles', models.CharField(max_length=50)),
                ('base_hp', models.IntegerField()),
                ('base_atk', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('base_sp_atk', models.IntegerField()),
                ('base_sp_def', models.IntegerField()),
                ('base_speed', models.IntegerField()),
                ('pokemon_image', models.ImageField(blank=True, null=True, upload_to='Pokemon_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('profile_pfp', models.URLField()),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.pokedex')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=12)),
                ('trade_date', models.DateTimeField(blank=True, null=True)),
                ('pokemon_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='pokemon_app.pokemon')),
                ('pokemon_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='pokemon_app.pokemon')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.user')),
            ],
        ),
    ]
