# Generated by Django 5.1.3 on 2024-12-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='base_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
