# Generated by Django 5.1.3 on 2024-12-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_alter_pokedex_base_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='base_exp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
