# Generated by Django 5.1.3 on 2024-12-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0004_profile_alter_pokemon_trainer_alter_trade_proposer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='pokemon_app.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposer', to='pokemon_app.profile'),
        ),
    ]
